<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Audit Report - {{ $audit->domain }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 40px;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #007bff;
            padding-bottom: 20px;
        }

        .header h1 {
            color: #007bff;
            font-size: 32px;
            margin-bottom: 10px;
        }

        .header .domain {
            font-size: 18px;
            color: #666;
        }

        .meta-info {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .meta-info p {
            margin-bottom: 8px;
        }

        .scores-container {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }

        .score-card {
            border: 2px solid #e9ecef;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
        }

        .score-card h3 {
            font-size: 16px;
            color: #495057;
            margin-bottom: 15px;
            text-transform: uppercase;
        }

        .score-value {
            font-size: 48px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .score-good {
            color: #28a745;
        }

        .score-average {
            color: #ffc107;
        }

        .score-poor {
            color: #dc3545;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e9ecef;
            text-align: center;
            color: #6c757d;
            font-size: 12px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Website Performance Audit</h1>
        <p class="domain">{{ $audit->domain }}</p>
    </div>

    <div class="meta-info">
        <p><strong>Audit ID:</strong> #{{ $audit->id }}</p>
        <p><strong>Email:</strong> {{ $audit->email }}</p>
        <p><strong>Generated:</strong> {{ $audit->created_at->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <h2 style="margin-bottom: 20px; color: #007bff;">Performance Scores</h2>

    <div class="scores-container">
        <div class="score-card">
            <h3>Performance</h3>
            <div
                class="score-value {{ $scores['performance']['score'] >= 0.9 ? 'score-good' : ($scores['performance']['score'] >= 0.5 ? 'score-average' : 'score-poor') }}">
                {{ round($scores['performance']['score'] * 100) }}
            </div>
            <p>out of 100</p>
        </div>

        <div class="score-card">
            <h3>Accessibility</h3>
            <div
                class="score-value {{ $scores['accessibility']['score'] >= 0.9 ? 'score-good' : ($scores['accessibility']['score'] >= 0.5 ? 'score-average' : 'score-poor') }}">
                {{ round($scores['accessibility']['score'] * 100) }}
            </div>
            <p>out of 100</p>
        </div>

        <div class="score-card">
            <h3>Best Practices</h3>
            <div
                class="score-value {{ $scores['best_practices']['score'] >= 0.9 ? 'score-good' : ($scores['best_practices']['score'] >= 0.5 ? 'score-average' : 'score-poor') }}">
                {{ round($scores['best_practices']['score'] * 100) }}
            </div>
            <p>out of 100</p>
        </div>

        <div class="score-card">
            <h3>SEO</h3>
            <div
                class="score-value {{ $scores['seo']['score'] >= 0.9 ? 'score-good' : ($scores['seo']['score'] >= 0.5 ? 'score-average' : 'score-poor') }}">
                {{ round($scores['seo']['score'] * 100) }}
            </div>
            <p>out of 100</p>
        </div>
    </div>

    <div class="footer">
        <p>Generated by EZAudit - Powered by Google Lighthouse</p>
        <p>This report provides insights based on Google's Lighthouse performance metrics.</p>
    </div>
</body>

</html>
